#Build settings
theme: minima
title: nattdev
author:
  name: nattdev
description: Aprendizaje y Desarrollo de código

show_excerpts: true

minima:
  social_links:
    github: nattdev

defaults:
  -
    scope:
      path: "notasycodigo" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      permalink: "/:categories/:title"
    scope:
      path: "proyectos" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      permalink: "/:categories/:title"
      