#Build settings
theme: minima
title: nattdev's homepage
author:
  name: nattdev
  email: email@email.com
description: Code notes for all

show_excerpts: true

minima:
  social_links:
    github: nattdev
